'use client';

import { useState, useEffect } from 'react';
import { useFormStore } from '@/store/form_store';
import { generateSummary } from '@/services/api';
import ReactMarkdown from 'react-markdown';

export default function SummaryPage() {
  const { answers, resetForm } = useFormStore();
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchSummary();
  }, []);

  const fetchSummary = async () => {
    setLoading(true);
    setError('');
    
    try {
      const allAnswers = answers.map((a) => ({
        question: a.questionTitle,
        answer: a.answerValue,
      }));

      const summaryText = await generateSummary({ allAnswers });
      setSummary(summaryText);
    } catch (err) {
      console.error('Error generating summary:', err);
      setError('Failed to generate summary. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleStartOver = () => {
    resetForm();
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto py-16 px-4 text-center">
        <div className="animate-pulse">
          <div className="text-6xl mb-4">✨</div>
          <h2 className="text-2xl font-bold text-gray-800 mb-2">
            Generating Your Creative Brief...
          </h2>
          <p className="text-gray-600">
            AI is crafting a professional summary of your campaign
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-4xl mx-auto py-16 px-4 text-center">
        <div className="bg-red-50 border-2 border-red-200 rounded-xl p-8">
          <div className="text-5xl mb-4">⚠️</div>
          <h2 className="text-2xl font-bold text-red-800 mb-2">{error}</h2>
          <button
            onClick={fetchSummary}
            className="mt-4 px-6 py-3 bg-red-600 text-white rounded-lg font-semibold hover:bg-red-700"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto py-8 px-4">
      {/* Header */}
      <div className="mb-8 text-center print:mb-6">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">
          🎉 Your UGC Creative Brief
        </h1>
        <p className="text-gray-600">
          Here's your professionally formatted campaign brief
        </p>
      </div>

      {/* Action Buttons */}
      <div className="mb-6 flex gap-4 justify-center print:hidden">
        <button
          onClick={handlePrint}
          className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors"
        >
          🖨️ Print / Save as PDF
        </button>
        <button
          onClick={handleStartOver}
          className="px-6 py-3 bg-gray-600 text-white rounded-lg font-semibold hover:bg-gray-700 transition-colors"
        >
          🔄 Create New Brief
        </button>
      </div>

      {/* Summary Content */}
      <div className="bg-white rounded-xl shadow-xl p-8 border-2 border-gray-200 print:shadow-none print:border-0">
        <div className="prose prose-lg max-w-none">
          <ReactMarkdown
            components={{
              h1: ({ node, ...props }) => (
                <h1 className="text-3xl font-bold text-gray-900 mb-4 mt-6" {...props} />
              ),
              h2: ({ node, ...props }) => (
                <h2 className="text-2xl font-bold text-gray-800 mb-3 mt-6" {...props} />
              ),
              h3: ({ node, ...props }) => (
                <h3 className="text-xl font-bold text-gray-800 mb-2 mt-4" {...props} />
              ),
              p: ({ node, ...props }) => (
                <p className="text-gray-700 mb-3 leading-relaxed" {...props} />
              ),
              ul: ({ node, ...props }) => (
                <ul className="list-disc list-inside mb-4 space-y-2" {...props} />
              ),
              li: ({ node, ...props }) => (
                <li className="text-gray-700" {...props} />
              ),
              strong: ({ node, ...props }) => (
                <strong className="font-bold text-gray-900" {...props} />
              ),
            }}
          >
            {summary}
          </ReactMarkdown>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-8 text-center text-sm text-gray-500 print:hidden">
        <p>Generated by NugVerse AI • {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
}

